#! /bin/bash

#=========================================================================
# Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
# Create project entry template script.
# 
#  1. Copy this file to the $GS_HOME/projects/<project=name> directory
#  2. Edit the following three shell variables as needed
#  3. Edit the project entry creation script to match the load specs for
#     your project
#  4. Implement your own helpOpts for additional options
#  5. Expand usage() as needed
#  
#=========================================================================

projectName="Seaside3"
projectDirectoryName="seaside"
logFile="projectLoad_${projectName}.log"

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name> [<group-name> ... ]

Create project entry node for $projectName in tODE /home for named stone.

With no <group-name> specified, the Development group is loaded. It is highly
recommended that you choose one or more web adaptors:

  - Zinc
  - FastCGI
  - Swazoo

If you are just getting started, I recommend that you choose the Zinc web
adaptor and the Examples group.

The tODE script 'webServer' is also created in the tODE /home/$projectDirName. 
The 'webServer' script can be used to start and stop a separate vm for running
the chose Seaside adaptor.  Use 'webServer -h' from within tODE for more 
details.

OPTIONS
  -h show usage

EXAMPLES
  $(basename $0) -h
  $(basename $0) devkit Examples Zinc

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions

getOpts_help $@ #parse standard (-h) options

if [ $# -eq 0 ]; then
  usage; exit 1
fi
stoneName="$1"
shift
$GS_HOME/bin/tode serverDoIt $stoneName 1> $GS_HOME/gemstone/stones/$stoneName/logs/$logFile << EOF
  | loads entry result |
  loads := #( Development $@ ) collect: [:each | each asString].
  entry := TDProjectSpecEntryDefinition new
    configuration: '${projectName}'
      version: '3.1.2'
      repository: 'http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main'
      loads: loads;
    status: #(#'active');
    yourself.
  result := entry createProjectEntryNode: '/home/${projectDirectoryName}'.
  ^result printString
EOF

scriptDir=$(dirname $0)
cp ${scriptDir}/webServer.ston $GS_HOME/tode/home/${projectDirectoryName}
