#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-n] [-s <snapshot-file-path>] <stone-name> <gemstone-version>

Create a new stone with the the given stone name with tODE installed. Start stone
and netldi unless -n is specified.

If the -s option is not specified, $GEMSTONE/bin/extent0.seaside.dbf will be used as 
the initial extent.

If you create a stone from an extent snapshot, you should use the -N
option to start the stone, the first time.

OPTIONS
  -h 
   display help
  -n
     No startStone, no startNetldi.
  -s <snapshot-file-path> 
     Path to snapshot file used to create stone.

EXAMPLES
  $(basename $0) -h
  $(basename $0) kit 3.2.1
"
HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi

snapshotFileArg=""
noRestartArg=""
while getopts "hns:" OPT ; do
  case "$OPT" in
    h) usage; exit 0;;
    n) noRestartArg=" -n ";;
    s) snapshotFileArg=" -s ${OPTARG} ";;
    *) usage; exit 1;;
  esac
done
shift $(($OPTIND - 1))

if [ $# -ne 2 ]; then
  usage; exit 1
fi
stoneName="$1"
gsvers="$2"

$GS_HOME/bin/createStone $noRestartArg $snapshotFileArg $stoneName $gsvers

$GS_HOME/bin/installTodeStone $stoneName

echo "...finished $(basename $0)"
