#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name>

Delete the stone with the given name. The stone is stopped before the 
$GS_HOME/gemstone/stones/<stone-name> directory is deleted. The 
$GS_HOME/tode/sys/stone/<stone-name> directory is deleted as well as the
$GS_HOME/tode/sys/local/client/descriptions/<stone-name> description file
is deleted.

OPTIONS
  -h
     display help

EXAMPLES
  $(basename $0) -h
  $(basename $0) kit

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions
getOpts_help $@

if [ $# -ne 1 ]; then
  usage; exit 1
fi
stoneName="$1"

echo "deleting old instance of stone $stoneName (stopping stone and netldi first)"
if [ -d $GS_HOME/gemstone/stones/$stoneName ] ; then
  $GS_HOME/bin/stopStone -b $stoneName
  rm -rf $GS_HOME/gemstone/stones/$stoneName
fi
if [ -d $GS_HOME/tode/sys/stones/$stoneName ] ; then
  rm -rf $GS_HOME/tode/sys/stones/$stoneName
fi
if [ -e $GS_HOME/tode/sys/local/client/descriptions//$stoneName ] ; then
  rm -rf $GS_HOME/tode/sys/local/client/descriptions//$stoneName
fi

echo "...finished $(basename $0)"
