#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <gemstone-version>

Copy the gci libraries for the given GemStone version to the
$GS_HOME/pharo directory.

OPTIONS
  -h display help

EXAMPLES
   $(basename $0) -h
   $(basename $0) 3.2.1

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions
getOpts_help $@

if [ $# -ne 1 ]; then
  usage; exit 1
fi
vers="$1"

echo "Copying gci files to pharo"
pharo_vm=$GS_HOME/pharo/pharo-vm
if [ ! -e "$pharo_vm" ]; then
  echo "Install Pharo"
  $GS_HOME/bin/installPharo
fi

# Detect operating system
PLATFORM="`uname -sm | tr ' ' '-'`"
# Macs with Core i7 use the same software as older Macs
[ $PLATFORM = "Darwin-x86_64" ] && PLATFORM="Darwin-i386"

case "$PLATFORM" in
  Linux-x86_64)
    gsvers="GemStone64Bit${vers}-x86_64.Linux"
    gs_product=$GS_HOME/gemstone/products/$gsvers
    cp $gs_product/lib32/lib* $pharo_vm
  ;;
  Darwin-i386)
    gsvers="GemStone64Bit${vers}-i386.Darwin"
    gs_product=$GS_HOME/gemstone/products/$gsvers
    cp $gs_product/lib32/lib* $pharo_vm/Pharo.app/Contents/MacOS/Plugins
  ;;
esac

echo "...finished $(basename $0)"
