#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h]

Download and install a Linux or Mac or Pharo3.0 VM, image and changes file.

OPTIONS
  -h display help

EXAMPLES
  $(basename $0) -h
  $(basename $0)

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions
getOpts_help $@

if [ $# -ne 0 ]; then
  usage; exit 1
fi
echo "Installing Pharo"

if [ -e "$GS_HOME/pharo/pharo-vm" ]; then
  echo "Pharo already installed. To reinstall delete Pharo directory and try again."
  exit 0
fi

# Look for wget to download Pharo
if [ -e "`which wget`" ]; then
    cmd="`which wget`"
else
    echo "[Error] wget is not available. Install wget and rerun this script."
    exit 1
fi

# Download Pharo

cd $GS_HOME/pharo
wget -O- get.pharo.org/vm30 | bash
wget -O- get.pharo.org/30 | bash

echo "...finished $(basename $0)"
