#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <gemstone-version>

Create a todeClient image on a remote machine. Runs the installGemstone (to acquire gci
libraries), createTodeImage and todeClient scripts.

OPTIONS
  -h display help

EXAMPLES
   $(basename $0) -h
   $(basename $0) 3.2.1

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions
getOpts_help $@

if [ $# -ne 1 ]; then
  usage; exit 1
fi
gsvers="$1"

$GS_HOME/bin/installGemStone $gsvers

$GS_HOME/bin/createTodeImage

$GS_HOME/bin/todeClient

echo "...finished $(basename $0)"
