#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <stone-name> <tode-command-line>

Execute the <tode-command-line> as a tODE command 

OPTIONS
  -h show usage

EXAMPLES
  $(basename $0) -h
  $(basename $0) devkit project load Seaside3
  $(basename $0) devkit eval \`3+4\`
  $(basename $0) devkit eval \`3+4\`\; eval \`self == 7 ifFalse: [ System logout ]\`

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
source ${GS_HOME}/bin/shFunctions

getOpts_help $@ #parse standard (-h) options

stoneName="$1"
shift

echo "performing: __$*__"
$GS_HOME/bin/tode todeIt $stoneName << EOF
$*
EOF

echo "...finished $(basename $0)"
