#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-b] <stone-name>

Stop the named stone. Any statmonitor processes associated 
with the stone will be stopped.

The netldi for the stone is left running unless the -b option
is specified.

OPTIONS
  -h display help
  -b stop the netldi for the stone

EXAMPLES
  $(basename $0) -h
  $(basename $0) kit

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"; exit 1
fi
stopNetldi=""
while getopts "bhns:" OPT ; do
  case "$OPT" in
    h) usage; exit 0;;
    b) stopNetldi="true";;
    *) usage; exit 1;;
  esac
done
shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
  usage; exit 1
fi
stoneName=$1
stonePath=$GS_HOME/gemstone/stones/${stoneName}

if [ -d "$stonePath" ] ; then
# set up stone environment
  pushd $stonePath >& /dev/null
  source $stonePath/stone.env
  popd >& /dev/null

  # stop the stone
  $GS_HOME/bin/gs/stopGemstone

  if [ "${stopNetldi}" = "true" ] ; then
    $GS_HOME/bin/stopNetldi $stoneName
  fi
fi

echo "...finished $(basename $0)"
