name: Client Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        gs_version: [ 2.4.8, 3.1.0.6, 3.2.17, 3.3.9, 3.4.5, 3.5.5, 3.6.1 ]
        test: [ Clients ]
        allowfailure: [ false ]
        include:
          - gs_version: 3.3.9
            test: Client
            client: Pharo3.0
            allowfailure: false
          - gs_version: 3.3.9
            test: Client
            client: Pharo6.1
            allowfailure: false
          - gs_version: 3.4.5
            test: Client
            client: Pharo3.0    
            allowfailure: false
          - gs_version: 3.4.5
            test: Client
            client: Pharo6.1
            allowfailure: false
          - gs_version: 3.5.5
            test: Client
            client: Pharo3.0
            allowfailure: false
          - gs_version: 3.5.5
            test: Client
            client: Pharo6.1
            allowfailure: false
          - gs_version: 3.6.1
            test: Client
            client: Pharo3.0
            allowfailure: false
          - gs_version: 3.6.1
            test: Client
            client: Pharo5.0
            allowfailure: false
          - gs_version: 3.6.1
            test: Client
            client: Pharo6.0
            allowfailure: false
          - gs_version: 3.6.1
            test: Client
            client: Pharo6.1
            allowfailure: false
          - gs_version: 3.6.1
            test: Client
            client: Pharo7.0
            allowfailure: false
          
    env:
      GS_VERSION: ${{ matrix.gs_version }}
      TEST: ${{ matrix.test }}
      UPGRADE_FROM: ${{ matrix.upgrade_from }}
      Client: ${{ matrix.client }}
    continue-on-error: ${{ matrix.allowfailure }}
    name: ${{ matrix.gs_version }} - ${{ matrix.test }} - ${{ matrix.upgrade_from }} - ${{ matrix.client }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Run tests
        run: |
          export GS_HOME="$(pwd)"
          export PATH=$GS_HOME/bin:$PATH
          export GS_TRAVIS=true
          export JAVA="/usr/bin/java"
          export CHROME_DRIVER_VERSION="87.0.4280.88"
          hostname
          cat /etc/hosts
          $GITHUB_WORKSPACE/tests/testTravisCI.sh
        shell: bash