name: smalltalkCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        gs_version: [ 2.4.8, 3.1.0.6, 3.2.17, 3.3.9, 3.4.5, 3.5.5, 3.6.1 ]
        allowfailure: [ false ]
        exclude:
          - gs_version: 3.1.0.6
            test: SmalltalkCI
          - gs_version: 3.2.17
            test: SmalltalkCI
          - gs_version: 3.3.9
            test: SmalltalkCI
    env:
      GS_VERSION: ${{ matrix.gs_version }}
      TEST: SmalltalkCI
    continue-on-error: ${{ matrix.allowfailure }}
    name: ${{ matrix.gs_version }} - SmalltalkCI
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          export GS_HOME="$(pwd)"
          export PATH=$GS_HOME/bin:$PATH
          export GS_TRAVIS=true
          hostname
          cat /etc/hosts
          $GITHUB_WORKSPACE/tests/testTravisCI.sh
        shell: bash