name: smalltalkCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        gs_version: [ 3.1.0.6, 3.2.17, 3.3.9, 3.4.5, 3.5.5, 3.6.1 ]
        test: [ UnitTests, BasicA, BasicB, Seaside3, SmalltalkCI ]
        exclude:
          - gs_version: 3.1.0.6
            test: Seaside3
          - gs_version: [ 3.1.0.6, 3.2.17, 3.3.9 ]
            test: SmalltalkCI
    env:
      GS_VERSION: ${{ matrix.gs_version }}
      TEST: ${{ matrix.test }}
    #continue-on-error: ${{ matrix.allowfailure }}
    name: ${{ matrix.gs_version }} - ${{ matrix.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Run tests
        run: |
          sudo hostname travis.dev
          export GS_HOME="$(pwd)"
          export PATH=$GS_HOME/bin:$PATH
          export GS_TRAVIS=true
          export JAVA="/usr/bin/java"
          export CHROME_DRIVER_VERSION="87.0.4280.88"
          hostname
          cat /etc/hosts
          $GITHUB_WORKSPACE/tests/testTravisCI.sh
        shell: bash