name: smalltalkCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        gs_version: [ 2.4.8, 3.1.0.6, 3.2.17, 3.3.9, 3.4.5, 3.5.5, 3.6.1 ]
        # test: [ UnitTests, BasicA, BasicB, Seaside3, SmalltalkCI ]
        test: [ UnitTests ]
        exclude:
          - gs_version: 3.1.0.6
            test: Seaside3
          - gs_version: 2.4.8
            test: Seaside3
          - gs_version: 3.1.0.6
            test: SmalltalkCI
          - gs_version: 3.2.17
            test: SmalltalkCI
          - gs_version: 3.3.9
            test: SmalltalkCI
        include:
          - gs_version: 3.4.5
            upgrade_from: 3.3.9
            test: Upgrade_unittest
          - gs_version: 3.5.1
            upgrade_from: 3.3.9
            test: Upgrade_unittest
          - gs_version: 3.3.4.3
            test: Error
          - gs_version: 3.4.5
            test: Install

          
    env:
      GS_VERSION: ${{ matrix.gs_version }}
      TEST: ${{ matrix.test }}
      UPGRADE_FROM: ${{ matrix.upgrade_from }}
    #continue-on-error: ${{ matrix.allowfailure }}
    name: ${{ matrix.gs_version }} - ${{ matrix.test }} - ${{ matrix.upgrade_from }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Run tests
        run: |
          export GS_HOME="$(pwd)"
          export PATH=$GS_HOME/bin:$PATH
          export GS_TRAVIS=true
          export JAVA="/usr/bin/java"
          export CHROME_DRIVER_VERSION="87.0.4280.88"
          hostname
          cat /etc/hosts
          $GITHUB_WORKSPACE/tests/testTravisCI.sh
        shell: bash